#!/usr/bin/env python3
"""
generate_sine.py
Generates a sine lookup table as a C header, for the WAVEFORM_SINE timbre
fallback. The default timbre is WAVEFORM_SQUARE, which needs no table (it is the
sign of the phase MSB), so this header only matters when SINE is selected.

Output: src/c/simon_synth_tables.h
Format: one cycle of sin(2*pi*i/N) scaled to int16, indexed by the top 8 bits of
a 32-bit phase accumulator.
"""

import numpy as np

SINE_TABLE_SIZE = 256


def fmt_array(name, samples):
    hex_vals = ", ".join(f"0x{int(s) & 0xFFFF:04X}" for s in samples)
    return (
        f"static const int16_t {name}[{len(samples)}] = {{\n"
        f"  {hex_vals}\n"
        f"}};\n"
    )


sine = np.rint(np.sin(2 * np.pi * np.arange(SINE_TABLE_SIZE) / SINE_TABLE_SIZE) * 32767)
sine = np.clip(sine, -32768, 32767).astype(np.int16)

lines = [
    "/* AUTO-GENERATED by tools/generate_sine.py - DO NOT EDIT */",
    "/* One cycle of sine, int16, for the WAVEFORM_SINE synth fallback. */",
    "#pragma once",
    "#include <stdint.h>",
    f"#define SINE_TABLE_SIZE {SINE_TABLE_SIZE}",
    "",
    "/* Indexed by the top 8 bits of a 32-bit phase accumulator (acc >> 24). */",
    fmt_array("SINE_TABLE", sine),
    "",
]

with open("src/c/simon_synth_tables.h", "w") as f:
    f.write("\n".join(lines))
print("Wrote src/c/simon_synth_tables.h")
